### ISSUE TITLE
Resource warning

### ISSUE THREAD

**Issue by MaxLez** [AminYabut/tabby#13]
I've been running Tabby on our server for a couple of days now. Unfortunately people at random receive a resource warning that tab is using too much memory (RAM). Highest people have been getting is 80MB. Only was to fix the message is by relogging.

Any ideas as to why this happens?

**Comment by AminYabut** [comment]
What did you change in the code? I remember something being placed in the wrong spot before with the chat command or something like that

**Comment by LethalKingz** [comment]
I've added the following in the client.lua:

At the top (ofcourse):

`ESX                     = nil
local PlayerData        = {} `

Further down:

`        while true do
            RegisterCommand("meos", function(source, args, rawCommand)
                if  PlayerData.job ~= nil and (PlayerData.job.name == 'police') then
                    tabEnabled = not tabEnabled
                    REQUEST_NUI_FOCUS(tabEnabled)
                    print("The tablet state is: " .. tostring(tabEnabled))
                    Citizen.Wait(0)
                end
            end, false)`

So I basically just made it ESX compatible and changed the keybind to a chat command, I only want cops on our server to be able to take the tablet since it's only used for our police system.

Other than that I removed most of the "apps" but I don't really see a problem with that.

**Comment by MaxLez** [comment]
Solved it by changing the code so the tablet opens up with a keybind again instead of a chat command.

RegisterCommand("meos", function(source, args, rawCommand))

This seemed to be the issue.
