### ISSUE TITLE
Can't load custom sites

### ISSUE THREAD

**Issue by royalistiqrp** [AminYabut/tabby#2]
First of all thank you for this script,
So there is a problem if I fill in a custom address like facebook.com or something. It doesn't load and I just see a blank page.

**Comment by AminYabut** [comment]
That is because the site you are trying to load doesn't allow the entire site to be iframed. This is a security measure used by many sites. You can test the pages by opening the page you made for the tablet in your web browser and checking the message in the f12 console menu. If the page shows then you can iframe it, if it doesn't it will tell you that xframe options won't allow it.

**Comment by royalistiqrp** [comment]
Okay thanks for your reply, will test it out soon.

**Comment by Alevhovic** [comment]
I don't have access to my "localhost/website" (write php), and i use the "opencad.html" without modification except the <iframe> line... I try on many browser (chrome, firefox, ie) and it works, but on game i have the white screen... Any idea ?

**Comment by MoravianLion** [comment]
Same problem here, opens everywhere, even in-game steam browser, but not in this amazing tablet :/
